// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://satsigmywganodvjcsip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhdHNpZ215d2dhbm9kdmpjc2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjEyNDksImV4cCI6MjA3MTUzNzI0OX0.i43PyCq0KjTMrzj4qYaMznWOOPK6cl9XRIhSQu6KNvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Note: Multiple GoTrueClient instances warning in development is normal
// and can be safely ignored. This happens due to React's hot reloading.